apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-front
  namespace: default
spec:
  interval: 1m
  releaseName: store-front
  chart:
    spec:
      chart: store-front
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system
  values:
    storeFront:
      nodeSelector:
        kubernetes.io/os: linux
      ports:
      - port: 80
        targetPort: 8080
      replicas: 5